numbers = [1, 2, 3, 4, 5]
print(numbers)
numbers.append(6)
print(numbers)
numbers.insert(2, -5) 
numbers.remove(5)
print(numbers)
print(len(numbers))
print(-5 in numbers)
numbers.clear()
print(numbers)
print(len(numbers))
print(-5 in numbers)
